<?php
namespace michaelmawhinney;

/**
 * Whois can perform WHOIS queries on domain names and IP addresses.
 *
 * @category WHOIS
 * @package Whois
 * @author Michael R Mawhinney JR <michael.mawhinney.jr@gmail.com>
 * @copyright 2018
 * @license https://opensource.org/licenses/MIT/ MIT
 * @version 0.8.0
 */
class Whois
{
    public static function search($keyword)
    {
        if (filter_var($keyword, FILTER_VALIDATE_IP) !== false) {
            return self::searchIp($keyword);
        } else if (filter_var($keyword, FILTER_VALIDATE_DOMAIN) !== false) {
            return self::searchDomain($keyword);
        } else {
            die("Error: invalid WHOIS search keyword");
        }
    }

    public static function root($domain)
    {
        $result = self::etld($domain);
        return $result["root"];
    }

    private static function etld($domain)
    {
        $d = explode(".", $domain);
        $sld = implode(".", array_slice($d, -2, 2));

        // first search for a matching country-coded SLD (ccSLD)
        // if no match, then assume a generic TLD (gTLD)
        if (in_array($sld, self::CCSLD_ARRAY)) {
            return array(
                "root" => implode(".", array_slice($d, -3, 3)),
                "etld" => implode(".", array_slice($d, -2, 2)),
                "tld" => end($d)
            );
        } else {
            return array(
                "root" => implode(".", array_slice($d, -2, 2)),
                "etld" => end($d),
                "tld" => end($d)
            );
        }
    }

    private static function searchDomain($domain)
    {
        $result = self::etld($domain);
        $root = $result["root"];
        $etld = $result["etld"];
        $tld = $result["tld"];

        if (array_key_exists($etld, self::WHOIS_SERVERS)) {
            $whois_server = self::WHOIS_SERVERS[$etld];
        } else if (array_key_exists($tld, self::WHOIS_SERVERS)) {
            $whois_server = self::WHOIS_SERVERS[$tld];
        } else {
            die("Error: no WHOIS server found");
        }

        $result = self::query($whois_server, $root);
        if ($result === false) {
            die("Error: no entry for $root on $whois_server");
        }

        return $result;
    }

    private static function searchIp($ip)
    {
        /*
            whois.arin.net (US, Canada)
            whois.ripe.net (Europe, Russia, Central Asia)
            whois.apnic.net (East Asia, Australia)
            whois.lacnic.net (Latin America -- but searches globally)
            whois.afrinic.net (Africa)
            whois.iana.org (fallback)
        */

        $registry = "whois.iana.org";
        if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) !== false) {
            $arr = explode(".", $ip);
            $octet = str_pad($arr[0], 3, "0", STR_PAD_LEFT);
            if (array_key_exists($octet, self::IPV4_REGISTRIES)) {
                if (self::IPV4_REGISTRIES[$octet] != "reserved") {
                    $registry = self::IPV4_REGISTRIES[$octet];
                }
            }
        } else if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false) {
            $arr = explode(":", $ip);
            $sextet1 = str_pad($arr[0], 4, "0", STR_PAD_LEFT);

            $a = array_filter(
				self::IPV6_REGISTRIES,
				function($k) use ($sextet1) {
					return hexdec($sextet1) >= hexdec($k);
				},
				ARRAY_FILTER_USE_KEY
			);

            $match_value = end($a);
            $match_key = key($a);
            if ($match_key == "2001") {
                $sextet2 = str_pad($arr[1], 4, "0", STR_PAD_LEFT);
                $b = array_filter(
					self::IPV6_REGISTRIES["2001"],
					function($k) use ($sextet2) {
						return hexdec($sextet2) >= hexdec($k);
					},
					ARRAY_FILTER_USE_KEY
				);
                $registry = end($b);
            } else {
                $registry = $match_value;
            }
        } else {
            throw new Exception("Invalid IP address");
        }

        if ($registry == "reserved") {
            $registry = "whois.iana.org";
        }

        $result = self::query($registry, $ip);
        if ($result === false) {
            throw new Exception("Error: no entry found for $ip");
        } else {
            return $result;
        }
    }

    private static function query($server, $keyword)
    {
        $handle = fsockopen($server, 43, $errno, $errstr, 10);
        if ($handle === false) {
            die("Socket Error $errno: $errstr");
        } else {
            fwrite($handle, $keyword . "\r\n");
            $contents = stream_get_contents($handle);
            fclose($handle);
            return $contents;
        }
    }

    const CCSLD_ARRAY = array(
        "12hp.at",
        "2ix.at",
        "4lima.at",
        "9guacu.br",
        "abc.br",
        "ac.at",
        "ac.il",
        "ac.kr",
        "ac.nz",
        "ac.ru",
        "ac.uk",
        "ac.za",
        "adm.br",
        "adv.br",
        "adygeya.ru",
        "aeroport.fr",
        "agr.br",
        "agric.za",
        "aju.br",
        "ak.us",
        "alt.za",
        "al.us",
        "am.br",
        "anani.br",
        "aparecida.br",
        "arq.br",
        "art.br",
        "ar.us",
        "assedic.fr",
        "asso.fr",
        "as.us",
        "ato.br",
        "avocat.fr",
        "avoues.fr",
        "av.tr",
        "az.us",
        "bashkiria.ru",
        "b.br",
        "bbs.tr",
        "belem.br",
        "bel.tr",
        "bhz.br",
        "bio.br",
        "bir.ru",
        "biz.at",
        "biz.tr",
        "biz.ua",
        "blog.br",
        "blogspot.fr",
        "blogspot.kr",
        "blogspot.ru",
        "bmd.br",
        "boavista.br",
        "bsb.br",
        "busan.kr",
        "campinagrande.br",
        "campinas.br",
        "ca.us",
        "caxias.br",
        "cbg.ru",
        "cci.fr",
        "cc.ua",
        "chambagri.fr",
        "cherkassy.ua",
        "cherkasy.ua",
        "chernigov.ua",
        "chernihiv.ua",
        "chernivtsi.ua",
        "chernovtsy.ua",
        "chirurgiens-dentistes-en-france.fr",
        "chirurgiens-dentistes.fr",
        "chungbuk.kr",
        "chungnam.kr",
        "cim.br",
        "ck.ua",
        "cloudns.us",
        "cng.br",
        "cnt.br",
        "cn.ua",
        "co.at",
        "co.il",
        "co.kr",
        "com.br",
        "com.es",
        "com.fr",
        "com.ru",
        "com.tr",
        "com.ua",
        "contagem.br",
        "co.nz",
        "coop.br",
        "co.ua",
        "co.uk",
        "co.us",
        "co.za",
        "cri.br",
        "crimea.ua",
        "cri.nz",
        "cr.ua",
        "ct.us",
        "cuiaba.br",
        "curitiba.br",
        "cv.ua",
        "daegu.kr",
        "daejeon.kr",
        "dagestan.ru",
        "dc.us",
        "def.br",
        "de.us",
        "dnepropetrovsk.ua",
        "dnipropetrovsk.ua",
        "dni.us",
        "dn.ua",
        "dominic.ua",
        "donetsk.ua",
        "dp.ua",
        "dr.tr",
        "drud.us",
        "ecn.br",
        "eco.br",
        "edu.br",
        "edu.es",
        "edu.ru",
        "edu.tr",
        "edu.ua",
        "edu.za",
        "emp.br",
        "eng.br",
        "es.kr",
        "esp.br",
        "etc.br",
        "eti.br",
        "experts-comptables.fr",
        "far.br",
        "fbx-os.fr",
        "fbxos.fr",
        "fed.us",
        "feira.br",
        "flog.br",
        "floripa.br",
        "fl.us",
        "fm.br",
        "fnd.br",
        "fortal.br",
        "fot.br",
        "foz.br",
        "freebox-os.fr",
        "freeboxos.fr",
        "fst.br",
        "futurehosting.at",
        "futuremailing.at",
        "g12.br",
        "gangwon.kr",
        "ga.us",
        "geek.nz",
        "gen.nz",
        "gen.tr",
        "geometre-expert.fr",
        "ggf.br",
        "gob.es",
        "goiania.br",
        "go.kr",
        "golffan.us",
        "gouv.fr",
        "gov.br",
        "gov.il",
        "gov.ru",
        "govt.nz",
        "gov.tr",
        "gov.ua",
        "gov.uk",
        "gov.za",
        "greta.fr",
        "grondar.za",
        "grozny.ru",
        "gru.br",
        "gu.us",
        "gv.at",
        "gwangju.kr",
        "gyeongbuk.kr",
        "gyeonggi.kr",
        "gyeongnam.kr",
        "health.nz",
        "hi.us",
        "hs.kr",
        "huissier-justice.fr",
        "ia.us",
        "idf.il",
        "id.us",
        "if.ua",
        "il.us",
        "imb.br",
        "incheon.kr",
        "ind.br",
        "inf.br",
        "info.at",
        "info.tr",
        "inf.ua",
        "int.ru",
        "in.ua",
        "in.us",
        "isa.us",
        "is-by.us",
        "ivano-frankivsk.ua",
        "iwi.nz",
        "jab.br",
        "jampa.br",
        "jdf.br",
        "jeju.kr",
        "jeonbuk.kr",
        "jeonnam.kr",
        "joinville.br",
        "jor.br",
        "jus.br",
        "k12.il",
        "k12.tr",
        "kalmykia.ru",
        "kep.tr",
        "kg.kr",
        "kharkiv.ua",
        "kharkov.ua",
        "kherson.ua",
        "khmelnitskiy.ua",
        "khmelnytskyi.ua",
        "kh.ua",
        "kids.us",
        "kiev.ua",
        "kirovograd.ua",
        "kiwi.nz",
        "km.ua",
        "kr.ua",
        "krym.ua",
        "ks.ua",
        "ks.us",
        "kustanai.ru",
        "kv.ua",
        "kyiv.ua",
        "ky.us",
        "land-4-sale.us",
        "la.us",
        "law.za",
        "leg.br",
        "lel.br",
        "lg.ua",
        "lima-city.at",
        "londrina.br",
        "ltd.ua",
        "ltd.uk",
        "lt.ua",
        "lugansk.ua",
        "lutsk.ua",
        "lviv.ua",
        "lv.ua",
        "macapa.br",
        "maceio.br",
        "manaus.br",
        "maori.nz",
        "marine.ru",
        "maringa.br",
        "mat.br",
        "ma.us",
        "md.us",
        "med.br",
        "medecin.fr",
        "me.uk",
        "me.us",
        "mil.br",
        "mil.kr",
        "mil.nz",
        "mil.ru",
        "mil.tr",
        "mil.za",
        "mi.us",
        "mk.ua",
        "mn.us",
        "mordovia.ru",
        "morena.br",
        "mo.us",
        "mp.br",
        "ms.kr",
        "msk.ru",
        "ms.us",
        "mt.us",
        "muni.il",
        "mus.br",
        "mykolaiv.ua",
        "mytis.ru",
        "nalchik.ru",
        "name.tr",
        "natal.br",
        "nc.tr",
        "nc.us",
        "nd.us",
        "ne.kr",
        "net.br",
        "net.il",
        "net.nz",
        "net.ru",
        "net.tr",
        "net.ua",
        "net.uk",
        "net.za",
        "ne.us",
        "ngo.za",
        "nhs.uk",
        "nh.us",
        "nikolaev.ua",
        "nis.za",
        "niteroi.br",
        "nj.us",
        "nm.us",
        "noip.us",
        "nom.es",
        "nom.fr",
        "nom.za",
        "notaires.fr",
        "not.br",
        "nov.ru",
        "nsn.us",
        "ntr.br",
        "nv.us",
        "nym.nz",
        "ny.us",
        "odesa.ua",
        "odessa.ua",
        "odo.br",
        "od.ua",
        "oh.us",
        "ok.us",
        "on-web.fr",
        "or.at",
        "org.br",
        "org.es",
        "org.il",
        "org.nz",
        "org.ru",
        "org.tr",
        "org.ua",
        "org.uk",
        "org.za",
        "or.kr",
        "or.us",
        "osasco.br",
        "palmas.br",
        "parliament.nz",
        "pa.us",
        "pe.kr",
        "pharmacien.fr",
        "plc.uk",
        "pl.ua",
        "poa.br",
        "pointto.us",
        "police.uk",
        "poltava.ua",
        "pol.tr",
        "port.fr",
        "ppg.br",
        "pp.ru",
        "pp.ua",
        "prd.fr",
        "presse.fr",
        "priv.at",
        "pro.br",
        "pr.us",
        "psc.br",
        "psi.br",
        "pvh.br",
        "pyatigorsk.ru",
        "qsl.br",
        "radio.br",
        "rec.br",
        "recife.br",
        "re.kr",
        "ribeirao.br",
        "rio.br",
        "riobranco.br",
        "riopreto.br",
        "ri.us",
        "rivne.ua",
        "rovno.ua",
        "rv.ua",
        "salvador.br",
        "sampa.br",
        "santamaria.br",
        "santoandre.br",
        "saobernardo.br",
        "saogonca.br",
        "sb.ua",
        "school.nz",
        "school.za",
        "sc.kr",
        "sc.us",
        "sd.us",
        "sebastopol.ua",
        "seoul.kr",
        "sevastopol.ua",
        "sjc.br",
        "slg.br",
        "slz.br",
        "sm.ua",
        "sorocaba.br",
        "spb.ru",
        "srv.br",
        "stuff-4-sale.us",
        "sumy.ua",
        "taxi.br",
        "tel.tr",
        "teo.br",
        "ternopil.ua",
        "test.ru",
        "te.ua",
        "the.br",
        "tm.fr",
        "tmp.br",
        "tm.za",
        "tn.us",
        "trd.br",
        "tur.br",
        "tv.br",
        "tv.tr",
        "tx.us",
        "udi.br",
        "ulsan.kr",
        "ut.us",
        "uzhgorod.ua",
        "uz.ua",
        "va.us",
        "vet.br",
        "veterinaire.fr",
        "vinnica.ua",
        "vinnytsia.ua",
        "vi.us",
        "vix.br",
        "vladikavkaz.ru",
        "vladimir.ru",
        "vlog.br",
        "vn.ua",
        "volyn.ua",
        "vt.us",
        "wa.us",
        "web.tr",
        "web.za",
        "wiki.br",
        "wi.us",
        "wv.us",
        "wy.us",
        "yalta.ua",
        "zaporizhzhe.ua",
        "zaporizhzhia.ua",
        "zhitomir.ua",
        "zhytomyr.ua",
        "zlg.br",
        "zp.ua",
        "zt.ua",
    );

    const WHOIS_SERVERS = array(
        "ae.org"                   => "whois.centralnic.com",
        "africa.com"               => "whois.centralnic.com",
        "ar.com"                   => "whois.centralnic.com",
        "br.com"                   => "whois.centralnic.com",
        "cn.com"                   => "whois.centralnic.com",
        "co.com"                   => "whois.nic.co.com",
        "com.de"                   => "whois.centralnic.com",
        "de.com"                   => "whois.centralnic.com",
        "eu.com"                   => "whois.centralnic.com",
        "eu.org"                   => "whois.eu.org",
        "gb.com"                   => "whois.centralnic.com",
        "gb.net"                   => "whois.centralnic.com",
        "gr.com"                   => "whois.centralnic.com",
        "hu.com"                   => "whois.centralnic.com",
        "hu.net"                   => "whois.centralnic.com",
        "in.net"                   => "whois.centralnic.com",
        "jp.net"                   => "whois.centralnic.com",
        "jpn.com"                  => "whois.centralnic.com",
        "kr.com"                   => "whois.centralnic.com",
        "mex.com"                  => "whois.centralnic.com",
        "no.com"                   => "whois.centralnic.com",
        "qc.com"                   => "whois.centralnic.com",
        "ro.com"                   => "whois.centralnic.com",
        "ru.com"                   => "whois.centralnic.com",
        "sa.com"                   => "whois.centralnic.com",
        "se.com"                   => "whois.centralnic.com",
        "se.net"                   => "whois.centralnic.com",
        "uk.com"                   => "whois.centralnic.com",
        "uk.net"                   => "whois.centralnic.com",
        "us.com"                   => "whois.centralnic.com",
        "us.org"                   => "whois.centralnic.com",
        "uy.com"                   => "whois.centralnic.com",
        "za.com"                   => "whois.centralnic.com",
        "abbott"                   => "whois.afilias-srs.net",
        "abogado"                  => "whois-dub.mm-registry.com",
        "ac"                       => "whois.nic.ac",
        "academy"                  => "whois.donuts.co",
        "accountant"               => "whois.nic.accountant",
        "accountants"              => "whois.donuts.co",
        "aco"                      => "whois.afilias-srs.net",
        "active"                   => "whois.afilias-srs.net",
        "actor"                    => "whois.unitedtld.com",
        "ads"                      => "domain-registry-whois.l.google.com",
        "adult"                    => "whois.afilias-srs.net",
        "ae"                       => "whois.aeda.net.ae",
        "co.ae"                    => "whois.aeda.net.ae",
        "net.ae"                   => "whois.aeda.net.ae",
        "org.ae"                   => "whois.aeda.net.ae",
        "sch.ae"                   => "whois.aeda.net.ae",
        "ac.ae"                    => "whois.aeda.net.ae",
        "mil.ae"                   => "whois.aeda.net.ae",
        "gov.ae"                   => "whois.aeda.net.ae",
        "aeg"                      => "whois.nic.aeg",
        "aero"                     => "whois.aero",
        "af"                       => "whois.nic.af",
        "afl"                      => "whois.nic.afl",
        "ag"                       => "whois.nic.ag",
        "agency"                   => "whois.donuts.co",
        "ai"                       => "whois.ai",
        "airforce"                 => "whois.unitedtld.com",
        "airtel"                   => "whois.nic.airtel",
        "al"                       => "whois.ripe.net",
        "allfinanz"                => "whois.ksregistry.net",
        "alsace"                   => "whois-alsace.nic.fr",
        "am"                       => "whois.amnic.net",
        "android"                  => "domain-registry-whois.l.google.com",
        "apartments"               => "whois.donuts.co",
        "app"                      => "whois.nic.google",
        "aquarelle"                => "whois-aquarelle.nic.fr",
        "ar"                       => "www.nic.ar",
        "edu.ar"                   => "www.riu.edu.ar",
        "archi"                    => "whois.ksregistry.net",
        "army"                     => "whois.rightside.co",
        "arpa"                     => "whois.iana.org",
        "arte"                     => "whois.nic.arte",
        "as"                       => "whois.nic.as",
        "asia"                     => "whois.nic.asia",
        "associates"               => "whois.donuts.co",
        "at"                       => "whois.nic.at",
        "biz.at"                   => "whois.biz.at",
        "info.at"                  => "whois.info.at",
        "priv.at"                  => "whois.nic.priv.at",
        "attorney"                 => "whois.rightside.co",
        "au"                       => "whois.audns.net.au",
        "asn.au"                   => "whois.ausregistry.net.au",
        "com.au"                   => "whois.ausregistry.net.au",
        "edu.au"                   => "whois.ausregistry.net.au",
        "id.au"                    => "whois.ausregistry.net.au",
        "net.au"                   => "whois.ausregistry.net.au",
        "org.au"                   => "whois.ausregistry.net.au",
        "auction"                  => "whois.unitedtld.com",
        "audio"                    => "whois.uniregistry.net",
        "auto"                     => "whois.uniregistry.net",
        "autos"                    => "whois.afilias-srs.net",
        "aw"                       => "whois.nic.aw",
        "ax"                       => "whois.ax",
        "az"                       => "whois.ripe.net",
        "ba"                       => "whois.ripe.net",
        "bar"                      => "whois.nic.bar",
        "barcelona"                => "whois.nic.barcelona",
        "bargains"                 => "whois.donuts.co",
        "band"                     => "whois.rightside.co",
        "bank"                     => "whois.nic.bank",
        "barclaycard"              => "whois.nic.barclaycard",
        "barclays"                 => "whois.nic.barclays",
        "bauhaus"                  => "whois.nic.bauhaus",
        "bayern"                   => "whois-dub.mm-registry.com",
        "bbc"                      => "whois.nic.bbc",
        "bbva"                     => "whois.nic.bbva",
        "bcn"                      => "whois.nic.bcn",
        "be"                       => "whois.dns.be",
        "beer"                     => "whois-dub.mm-registry.com",
        "bentley"                  => "whois.nic.bentley",
        "berlin"                   => "whois.nic.berlin",
        "best"                     => "whois.nic.best",
        "bet"                      => "whois.afilias.net",
        "bg"                       => "whois.register.bg",
        "bi"                       => "whois1.nic.bi",
        "bid"                      => "whois.nic.bid",
        "bike"                     => "whois.donuts.co",
        "bio"                      => "whois.ksregistry.net",
        "bingo"                    => "whois.donuts.co",
        "biz"                      => "whois.biz",
        "bj"                       => "whois.nic.bj",
        "blackfriday"              => "whois.uniregistry.net",
        "black"                    => "whois.afilias.net",
        "blue"                     => "whois.afilias.net",
        "bms"                      => "whois.nic.bms",
        "bmw"                      => "whois.ksregistry.net",
        "bn"                       => "whois.bnnic.bn",
        "bnl"                      => "whois.afilias-srs.net",
        "bnpparibas"               => "whois.afilias-srs.net",
        "bo"                       => "whois.nic.bo",
        "boats"                    => "whois.afilias-srs.net",
        "bom"                      => "whois.gtlds.nic.br",
        "bond"                     => "whois.nic.bond",
        "boo"                      => "domain-registry-whois.l.google.com",
        "boots"                    => "whois.nic.boots",
        "boutique"                 => "whois.donuts.co",
        "br"                       => "whois.registro.br",
        "bradesco"                 => "whois-cl01.mm-registry.com",
        "bridgestone"              => "whois.nic.bridgestone",
        "broker"                   => "whois.nic.broker",
        "brother"                  => "whois.nic.brother",
        "brussels"                 => "whois.nic.brussels",
        "bs"                       => "www.register.bs",
        "budapest"                 => "whois-dub.mm-registry.com",
        "builders"                 => "whois.donuts.co",
        "build"                    => "whois.nic.build",
        "business"                 => "whois.donuts.co",
        "buzz"                     => "whois.nic.buzz",
        "bv"                       => "whois.ripe.net",
        "bw"                       => "whois.nic.net.bw",
        "by"                       => "whois.cctld.by",
        "bz"                       => "whois.belizenic.bz",
        "bzh"                      => "whois-bzh.nic.fr",
        "ca"                       => "whois.cira.ca",
        "co.ca"                    => "whois.co.ca",
        "cab"                      => "whois.donuts.co",
        "cafe"                     => "whois.donuts.co",
        "cal"                      => "domain-registry-whois.l.google.com",
        "camera"                   => "whois.donuts.co",
        "camp"                     => "whois.donuts.co",
        "cancerresearch"           => "whois.nic.cancerresearch",
        "canon"                    => "whois.nic.canon",
        "capetown"                 => "capetown-whois.registry.net.za",
        "capital"                  => "whois.donuts.co",
        "car"                      => "whois.uniregistry.net",
        "cards"                    => "whois.donuts.co",
        "career"                   => "whois.nic.career",
        "careers"                  => "whois.donuts.co",
        "care"                     => "whois.donuts.co",
        "cars"                     => "whois.uniregistry.net",
        "casa"                     => "whois-dub.mm-registry.com",
        "cash"                     => "whois.donuts.co",
        "casino"                   => "whois.donuts.co",
        "catering"                 => "whois.donuts.co",
        "cat"                      => "whois.cat",
        "cba"                      => "whois.nic.cba",
        "cc"                       => "ccwhois.verisign-grs.com",
        "cd"                       => "whois.nic.cd",
        "ceb"                      => "whois.afilias-srs.net",
        "center"                   => "whois.donuts.co",
        "ceo"                      => "whois.nic.ceo",
        "cern"                     => "whois.afilias-srs.net",
        "cf"                       => "whois.dot.cf",
        "cfa"                      => "whois.nic.cfa",
        "cfd"                      => "whois.nic.cfd",
        "cg"                       => "www.nic.cg",
        "ch"                       => "whois.nic.ch",
        "chanel"                   => "whois.nic.chanel",
        "channel"                  => "domain-registry-whois.l.google.com",
        "chat"                     => "whois.donuts.co",
        "cheap"                    => "whois.donuts.co",
        "christmas"                => "whois.uniregistry.net",
        "chrome"                   => "domain-registry-whois.l.google.com",
        "church"                   => "whois.donuts.co",
        "ci"                       => "whois.nic.ci",
        "cipriani"                 => "whois.afilias-srs.net",
        "city"                     => "whois.donuts.co",
        "cl"                       => "whois.nic.cl",
        "claims"                   => "whois.donuts.co",
        "cleaning"                 => "whois.donuts.co",
        "click"                    => "whois.uniregistry.net",
        "clinic"                   => "whois.donuts.co",
        "clothing"                 => "whois.donuts.co",
        "cloud"                    => "whois.nic.cloud",
        "club"                     => "whois.nic.club",
        "clubmed"                  => "whois.nic.clubmed",
        "cm"                       => "whois.netcom.cm",
        "co.cm"                    => "whois.netcom.cm",
        "com.cm"                   => "whois.netcom.cm",
        "net.cm"                   => "whois.netcom.cm",
        "cn"                       => "whois.cnnic.cn",
        "co"                       => "whois.nic.co",
        "coach"                    => "whois.donuts.co",
        "codes"                    => "whois.donuts.co",
        "coffee"                   => "whois.donuts.co",
        "college"                  => "whois.nic.college",
        "cologne"                  => "whois-fe1.pdt.cologne.tango.knipp.de",
        "com"                      => "whois.verisign-grs.com",
        "commbank"                 => "whois.nic.commbank",
        "community"                => "whois.donuts.co",
        "company"                  => "whois.donuts.co",
        "computer"                 => "whois.donuts.co",
        "condos"                   => "whois.donuts.co",
        "construction"             => "whois.donuts.co",
        "consulting"               => "whois.unitedtld.com",
        "contractors"              => "whois.donuts.co",
        "cooking"                  => "whois-dub.mm-registry.com",
        "cool"                     => "whois.donuts.co",
        "coop"                     => "whois.nic.coop",
        "corsica"                  => "whois-corsica.nic.fr",
        "country"                  => "whois-dub.mm-registry.com",
        "coupons"                  => "whois.donuts.co",
        "courses"                  => "whois.aridnrs.net.au",
        "cr"                       => "whois.nic.cr",
        "credit"                   => "whois.donuts.co",
        "creditcard"               => "whois.donuts.co",
        "cricket"                  => "whois.nic.cricket",
        "cruises"                  => "whois.donuts.co",
        "csc"                      => "whois.nic.csc",
        "cu"                       => "www.nic.cu",
        "cuisinella"               => "whois.nic.cuisinella",
        "cx"                       => "whois.nic.cx",
        "cy"                       => "whois.ripe.net",
        "cymru"                    => "whois.nic.cymru",
        "cyou"                     => "whois.afilias-srs.net",
        "cz"                       => "whois.nic.cz",
        "dabur"                    => "whois.afilias-srs.net",
        "dad"                      => "domain-registry-whois.l.google.com",
        "dance"                    => "whois.unitedtld.com",
        "date"                     => "whois.nic.date",
        "dating"                   => "whois.donuts.co",
        "datsun"                   => "whois.nic.gmo",
        "day"                      => "domain-registry-whois.l.google.com",
        "dclk"                     => "domain-registry-whois.l.google.com",
        "de"                       => "whois.denic.de",
        "com.de"                   => "whois.centralnic.com",
        "deals"                    => "whois.donuts.co",
        "degree"                   => "whois.rightside.co",
        "delivery"                 => "whois.donuts.co",
        "delta"                    => "whois.afilias-srs.net",
        "democrat"                 => "whois.unitedtld.com",
        "dental"                   => "whois.donuts.co",
        "dentist"                  => "whois.rightside.co",
        "desi"                     => "whois.ksregistry.net",
        "design"                   => "whois.nic.design",
        "dev"                      => "domain-registry-whois.l.google.com",
        "diamonds"                 => "whois.donuts.co",
        "diet"                     => "whois.uniregistry.net",
        "digital"                  => "whois.donuts.co",
        "direct"                   => "whois.donuts.co",
        "directory"                => "whois.donuts.co",
        "discount"                 => "whois.donuts.co",
        "dk"                       => "whois.dk-hostmaster.dk",
        "dm"                       => "whois.nic.dm",
        "domains"                  => "whois.donuts.co",
        "do"                       => "www.nic.do",
        "docs"                     => "domain-registry-whois.l.google.com",
        "dog"                      => "whois.donuts.co",
        "doha"                     => "whois.nic.doha",
        "doosan"                   => "whois.nic.doosan",
        "download"                 => "whois.nic.download",
        "drive"                    => "whois.nic.google",
        "durban"                   => "durban-whois.registry.net.za",
        "dvag"                     => "whois.ksregistry.net",
        "dz"                       => "whois.nic.dz",
        "eat"                      => "domain-registry-whois.l.google.com",
        "ec"                       => "whois.nic.ec",
        "edu"                      => "whois.educause.edu",
        "education"                => "whois.donuts.co",
        "ee"                       => "whois.tld.ee",
        "eg"                       => "whois.ripe.net",
        "email"                    => "whois.donuts.co",
        "emerck"                   => "whois.afilias-srs.net",
        "energy"                   => "whois.donuts.co",
        "engineer"                 => "whois.rightside.co",
        "engineering"              => "whois.donuts.co",
        "enterprises"              => "whois.donuts.co",
        "epson"                    => "whois.aridnrs.net.au",
        "equipment"                => "whois.donuts.co",
        "erni"                     => "whois.nic.erni",
        "es"                       => "whois.nic.es",
        "esq"                      => "domain-registry-whois.l.google.com",
        "estate"                   => "whois.donuts.co",
        "eu"                       => "whois.eu",
        "eurovision"               => "whois.nic.eurovision",
        "eus"                      => "whois.eus.coreregistry.net",
        "events"                   => "whois.donuts.co",
        "exchange"                 => "whois.donuts.co",
        "expert"                   => "whois.donuts.co",
        "exposed"                  => "whois.donuts.co",
        "express"                  => "whois.donuts.co",
        "fage"                     => "whois.afilias-srs.net",
        "fail"                     => "whois.donuts.co",
        "faith"                    => "whois.nic.faith",
        "family"                   => "whois.rightside.co",
        "fan"                      => "whois.nic.fan",
        "fans"                     => "whois.nic.fans",
        "farm"                     => "whois.donuts.co",
        "fashion"                  => "whois-dub.mm-registry.com",
        "feedback"                 => "whois.nic.feedback",
        "fi"                       => "whois.fi",
        "film"                     => "whois.nic.film",
        "final"                    => "whois.gtlds.nic.br",
        "finance"                  => "whois.donuts.co",
        "financial"                => "whois.donuts.co",
        "firmdale"                 => "whois.nic.firmdale",
        "fishing"                  => "whois-dub.mm-registry.com",
        "fish"                     => "whois.donuts.co",
        "fit"                      => "whois-dub.mm-registry.com",
        "fitness"                  => "whois.donuts.co",
        "fj"                       => "whois.usp.ac.fj",
        "flights"                  => "whois.donuts.co",
        "florist"                  => "whois.donuts.co",
        "flowers"                  => "whois.uniregistry.net",
        "flsmidth"                 => "whois.ksregistry.net",
        "fly"                      => "domain-registry-whois.l.google.com",
        "fm"                       => "whois.nic.fm",
        "fo"                       => "whois.nic.fo",
        "foo"                      => "domain-registry-whois.l.google.com",
        "football"                 => "whois.donuts.co",
        "forex"                    => "whois.nic.forex",
        "forsale"                  => "whois.unitedtld.com",
        "forum"                    => "whois.nic.forum",
        "foundation"               => "whois.donuts.co",
        "fr"                       => "whois.nic.fr",
        "frl"                      => "whois.nic.frl",
        "frogans"                  => "whois-frogans.nic.fr",
        "fund"                     => "whois.donuts.co",
        "furniture"                => "whois.donuts.co",
        "futbol"                   => "whois.unitedtld.com",
        "fyi"                      => "whois.donuts.co",
        "gallery"                  => "whois.donuts.co",
        "gal"                      => "whois.gal.coreregistry.net",
        "game"                     => "whois.uniregistry.net",
        "garden"                   => "whois-dub.mm-registry.com",
        "gbiz"                     => "domain-registry-whois.l.google.com",
        "gd"                       => "whois.nic.gd",
        "gdn"                      => "whois.nic.gdn",
        "gea"                      => "whois.afilias-srs.net",
        "gent"                     => "whois.nic.gent",
        "genting"                  => "whois.nic.genting",
        "gg"                       => "whois.gg",
        "ggee"                     => "whois.nic.ggee",
        "gi"                       => "whois2.afilias-grs.net",
        "gift"                     => "whois.uniregistry.net",
        "gifts"                    => "whois.donuts.co",
        "gives"                    => "whois.rightside.co",
        "giving"                   => "whois.nic.giving",
        "gl"                       => "whois.nic.gl",
        "glass"                    => "whois.donuts.co",
        "gle"                      => "domain-registry-whois.l.google.com",
        "global"                   => "whois.nic.global",
        "globo"                    => "whois.gtlds.nic.br",
        "gm"                       => "whois.ripe.net",
        "gmail"                    => "domain-registry-whois.l.google.com",
        "gmx"                      => "whois-fe1.gmx.tango.knipp.de",
        "gold"                     => "whois.donuts.co",
        "goldpoint"                => "whois.nic.goldpoint",
        "golf"                     => "whois.donuts.co",
        "goo"                      => "whois.nic.gmo",
        "goog"                     => "domain-registry-whois.l.google.com",
        "google"                   => "domain-registry-whois.l.google.com",
        "gop"                      => "whois-cl01.mm-registry.com",
        "gov"                      => "whois.dotgov.gov",
        "gq"                       => "whois.dominio.gq",
        "gr"                       => "whois.ripe.net",
        "graphics"                 => "whois.donuts.co",
        "gratis"                   => "whois.donuts.co",
        "green"                    => "whois.afilias.net",
        "gripe"                    => "whois.donuts.co",
        "group"                    => "whois.donuts.co",
        "gs"                       => "whois.nic.gs",
        "gt"                       => "www.gt",
        "guge"                     => "domain-registry-whois.l.google.com",
        "guide"                    => "whois.donuts.co",
        "guitars"                  => "whois.uniregistry.net",
        "guru"                     => "whois.donuts.co",
        "gy"                       => "whois.registry.gy",
        "hamburg"                  => "whois.nic.hamburg",
        "hangout"                  => "domain-registry-whois.l.google.com",
        "haus"                     => "whois.unitedtld.com",
        "healthcare"               => "whois.donuts.co",
        "help"                     => "whois.uniregistry.net",
        "here"                     => "domain-registry-whois.l.google.com",
        "hermes"                   => "whois.afilias-srs.net",
        "hiphop"                   => "whois.uniregistry.net",
        "hitachi"                  => "whois.nic.gmo",
        "hiv"                      => "whois.afilias-srs.net",
        "hk"                       => "whois.hkirc.hk",
        "hn"                       => "whois.nic.hn",
        "hockey"                   => "whois.donuts.co",
        "holdings"                 => "whois.donuts.co",
        "holiday"                  => "whois.donuts.co",
        "homedepot"                => "whois.afilias-srs.net",
        "homes"                    => "whois.afilias-srs.net",
        "honda"                    => "whois.nic.honda",
        "horse"                    => "whois-dub.mm-registry.com",
        "host"                     => "whois.nic.host",
        "hosting"                  => "whois.uniregistry.net",
        "house"                    => "whois.donuts.co",
        "how"                      => "domain-registry-whois.l.google.com",
        "hr"                       => "whois.dns.hr",
        "ht"                       => "whois.nic.ht",
        "hu"                       => "whois.nic.hu",
        "hyundai"                  => "whois.nic.hyundai",
        "ibm"                      => "whois.nic.ibm",
        "icbc"                     => "whois.afilias-srs.net",
        "ice"                      => "whois.nic.ice",
        "icu"                      => "whois.nic.icu",
        "id"                       => "whois.pandi.or.id",
        "ie"                       => "whois.domainregistry.ie",
        "ifm"                      => "whois.nic.ifm",
        "iinet"                    => "whois.aridnrs.net.au",
        "il"                       => "whois.isoc.org.il",
        "im"                       => "whois.nic.im",
        "immo"                     => "whois.donuts.co",
        "immobilien"               => "whois.unitedtld.com",
        "in"                       => "whois.inregistry.net",
        "industries"               => "whois.donuts.co",
        "infiniti"                 => "whois.nic.gmo",
        "info"                     => "whois.afilias.net",
        "ing"                      => "domain-registry-whois.l.google.com",
        "ink"                      => "whois.nic.ink",
        "institute"                => "whois.donuts.co",
        "insure"                   => "whois.donuts.co",
        "int"                      => "whois.iana.org",
        "international"            => "whois.donuts.co",
        "investments"              => "whois.donuts.co",
        "io"                       => "whois.nic.io",
        "iq"                       => "whois.cmc.iq",
        "ir"                       => "whois.nic.ir",
        "irish"                    => "whois.afilias-srs.net",
        "is"                       => "whois.isnic.is",
        "ist"                      => "whois.afilias-srs.net",
        "istanbul"                 => "whois.afilias-srs.net",
        "it"                       => "whois.nic.it",
        "java"                     => "whois.nic.java",
        "jcb"                      => "whois.nic.gmo",
        "je"                       => "whois.je",
        "jetzt"                    => "whois.nic.jetzt",
        "jewelry"                  => "whois.donuts.co",
        "jll"                      => "whois.afilias-srs.net",
        "jobs"                     => "jobswhois.verisign-grs.com",
        "joburg"                   => "joburg-whois.registry.net.za",
        "jp"                       => "whois.jprs.jp",
        "juegos"                   => "whois.uniregistry.net",
        "kaufen"                   => "whois.unitedtld.com",
        "kddi"                     => "whois.nic.kddi",
        "ke"                       => "whois.kenic.or.ke",
        "kg"                       => "whois.domain.kg",
        "ki"                       => "whois.nic.ki",
        "kia"                      => "whois.nic.kia",
        "kim"                      => "whois.afilias.net",
        "kitchen"                  => "whois.donuts.co",
        "kiwi"                     => "whois.nic.kiwi",
        "koeln"                    => "whois-fe1.pdt.koeln.tango.knipp.de",
        "komatsu"                  => "whois.nic.komatsu",
        "kr"                       => "whois.kr",
        "krd"                      => "whois.aridnrs.net.au",
        "ky"                       => "whois.kyregistry.ky",
        "kyoto"                    => "whois.nic.kyoto",
        "kz"                       => "whois.nic.kz",
        "la"                       => "whois.nic.la",
        "lacaixa"                  => "whois.nic.lacaixa",
        "lancaster"                => "whois-lancaster.nic.fr",
        "land"                     => "whois.donuts.co",
        "lasalle"                  => "whois.afilias-srs.net",
        "lat"                      => "whois.nic.lat",
        "latrobe"                  => "whois.nic.latrobe",
        "law"                      => "whois-dub.mm-registry.com",
        "lawyer"                   => "whois.rightside.co",
        "lb"                       => "cgi.aub.edu.lb",
        "lc"                       => "whois2.afilias-grs.net",
        "lds"                      => "whois.afilias-srs.net",
        "lease"                    => "whois.donuts.co",
        "leclerc"                  => "whois-leclerc.nic.fr",
        "legal"                    => "whois.donuts.co",
        "lexus"                    => "whois.nic.lexus",
        "lgbt"                     => "whois.afilias.net",
        "li"                       => "whois.nic.li",
        "liaison"                  => "whois.nic.liaison",
        "lidl"                     => "whois.nic.lidl",
        "life"                     => "whois.donuts.co",
        "lighting"                 => "whois.donuts.co",
        "limited"                  => "whois.donuts.co",
        "limo"                     => "whois.donuts.co",
        "linde"                    => "whois.nic.linde",
        "link"                     => "whois.uniregistry.net",
        "live"                     => "whois.rightside.co",
        "lixil"                    => "whois.nic.lixil",
        "lk"                       => "whois.nic.lk",
        "loan"                     => "whois.nic.loan",
        "loans"                    => "whois.donuts.co",
        "lol"                      => "whois.uniregistry.net",
        "london"                   => "whois-lon.mm-registry.com",
        "lotte"                    => "whois.nic.lotte",
        "lotto"                    => "whois.afilias.net",
        "love"                     => "whois.nic.love",
        "lt"                       => "whois.domreg.lt",
        "ltd"                      => "whois.donuts.co",
        "ltda"                     => "whois.afilias-srs.net",
        "lu"                       => "whois.dns.lu",
        "luxe"                     => "whois-dub.mm-registry.com",
        "luxury"                   => "whois.nic.luxury",
        "lv"                       => "whois.nic.lv",
        "ly"                       => "whois.nic.ly",
        "ma"                       => "whois.registre.ma",
        "madrid"                   => "whois.madrid.rs.corenic.net",
        "maison"                   => "whois.donuts.co",
        "man"                      => "whois.nic.man",
        "management"               => "whois.donuts.co",
        "mango"                    => "whois.mango.coreregistry.net",
        "market"                   => "whois.rightside.co",
        "markets"                  => "whois.nic.markets",
        "marketing"                => "whois.donuts.co",
        "marriott"                 => "whois.afilias-srs.net",
        "mba"                      => "whois.donuts.co",
        "md"                       => "whois.nic.md",
        "me"                       => "whois.nic.me",
        "media"                    => "whois.donuts.co",
        "meet"                     => "whois.afilias.net",
        "melbourne"                => "whois.aridnrs.net.au",
        "meme"                     => "domain-registry-whois.l.google.com",
        "memorial"                 => "whois.donuts.co",
        "men"                      => "whois.nic.men",
        "menu"                     => "whois.nic.menu",
        "mg"                       => "whois.nic.mg",
        "miami"                    => "whois-dub.mm-registry.com",
        "mini"                     => "whois.ksregistry.net",
        "mk"                       => "whois.marnet.mk",
        "ml"                       => "whois.dot.ml",
        "mma"                      => "whois-mma.nic.fr",
        "mn"                       => "whois.nic.mn",
        "mo"                       => "whois.monic.mo",
        "mobi"                     => "whois.dotmobiregistry.net",
        "moda"                     => "whois.unitedtld.com",
        "moe"                      => "whois.nic.moe",
        "mom"                      => "whois.uniregistry.net",
        "monash"                   => "whois.nic.monash",
        "money"                    => "whois.donuts.co",
        "mormon"                   => "whois.afilias-srs.net",
        "mortgage"                 => "whois.rightside.co",
        "moscow"                   => "whois.nic.moscow",
        "motorcycles"              => "whois.afilias-srs.net",
        "mov"                      => "domain-registry-whois.l.google.com",
        "movie"                    => "whois.donuts.co",
        "movistar"                 => "whois-fe.movistar.tango.knipp.de",
        "ms"                       => "whois.nic.ms",
        "mt"                       => "whois.nic.org.mt",
        "mtn"                      => "whois.nic.mtn",
        "mtpc"                     => "whois.nic.gmo",
        "mtr"                      => "whois.nic.mtr",
        "mu"                       => "whois.nic.mu",
        "museum"                   => "whois.museum",
        "mutuelle"                 => "whois-mutuelle.nic.fr",
        "mw"                       => "www.tarsus.net",
        "mx"                       => "whois.mx",
        "my"                       => "whois.mynic.my",
        "mz"                       => "whois.nic.mz",
        "na"                       => "whois.na-nic.com.na",
        "nadex"                    => "whois.nic.nadex",
        "name"                     => "whois.nic.name",
        "navy"                     => "whois.rightside.co",
        "nc"                       => "whois.nc",
        "nec"                      => "whois.nic.nec",
        "net"                      => "whois.verisign-grs.com",
        "netbank"                  => "whois.nic.netbank",
        "network"                  => "whois.donuts.co",
        "new"                      => "domain-registry-whois.l.google.com",
        "news"                     => "whois.rightside.co",
        "nexus"                    => "domain-registry-whois.l.google.com",
        "nf"                       => "whois.nic.nf",
        "ng"                       => "whois.nic.net.ng",
        "ngo"                      => "whois.publicinterestregistry.net",
        "nico"                     => "whois.nic.nico",
        "ninja"                    => "whois.unitedtld.com",
        "nissan"                   => "whois.nic.gmo",
        "nl"                       => "whois.domain-registry.nl",
        "no"                       => "whois.norid.no",
        "nokia"                    => "whois.afilias-srs.net",
        "nra"                      => "whois.afilias-srs.net",
        "nrw"                      => "whois.nic.nrw",
        "nu"                       => "whois.iis.nu",
        "nz"                       => "whois.srs.net.nz",
        "obi"                      => "whois.nic.obi",
        "om"                       => "whois.registry.om",
        "omega"                    => "whois.nic.omega",
        "one"                      => "whois.nic.one",
        "ong"                      => "whois.publicinterestregistry.net",
        "onl"                      => "whois.afilias-srs.net",
        "online"                   => "whois.centralnic.com",
        "ooo"                      => "whois.nic.ooo",
        "oracle"                   => "whois.nic.oracle",
        "orange"                   => "whois.nic.orange",
        "org"                      => "whois.pir.org",
        "organic"                  => "whois.afilias.net",
        "osaka"                    => "whois.nic.osaka",
        "ovh"                      => "whois-ovh.nic.fr",
        "pa"                       => "www.nic.pa",
        "page"                     => "domain-registry-whois.l.google.com",
        "paris"                    => "whois-paris.nic.fr",
        "partners"                 => "whois.donuts.co",
        "parts"                    => "whois.donuts.co",
        "party"                    => "whois.nic.party",
        "pe"                       => "kero.yachay.pe",
        "pet"                      => "whois.afilias.net",
        "pf"                       => "whois.registry.pf",
        "philips"                  => "whois.nic.philips",
        "photography"              => "whois.donuts.co",
        "photo"                    => "whois.uniregistry.net",
        "photos"                   => "whois.donuts.co",
        "physio"                   => "whois.nic.physio",
        "pics"                     => "whois.uniregistry.net",
        "pictures"                 => "whois.donuts.co",
        "pink"                     => "whois.afilias.net",
        "pizza"                    => "whois.donuts.co",
        "pk"                       => "pknic.net.pk",
        "pl"                       => "whois.dns.pl",
        "co.pl"                    => "whois.co.pl",
        "place"                    => "whois.donuts.co",
        "play"                     => "whois.nic.google",
        "plumbing"                 => "whois.donuts.co",
        "plus"                     => "whois.donuts.co",
        "pm"                       => "whois.nic.pm",
        "pohl"                     => "whois.ksregistry.net",
        "poker"                    => "whois.afilias.net",
        "porn"                     => "whois.afilias-srs.net",
        "post"                     => "whois.dotpostregistry.net",
        "pr"                       => "whois.nic.pr",
        "press"                    => "whois.nic.press",
        "pro"                      => "whois.dotproregistry.net",
        "prod"                     => "domain-registry-whois.l.google.com",
        "productions"              => "whois.donuts.co",
        "prof"                     => "domain-registry-whois.l.google.com",
        "properties"               => "whois.donuts.co",
        "property"                 => "whois.uniregistry.net",
        "protection"               => "whois.nic.protection",
        "ps"                       => "whois.pnina.ps",
        "pt"                       => "whois.dns.pt",
        "pub"                      => "whois.unitedtld.com",
        "pw"                       => "whois.nic.pw",
        "qa"                       => "whois.registry.qa",
        "qpon"                     => "whois.nic.qpon",
        "quebec"                   => "whois.nic.quebec",
        "racing"                   => "whois.nic.racing",
        "re"                       => "whois.nic.re",
        "realty"                   => "whois.nic.realty",
        "recipes"                  => "whois.donuts.co",
        "red"                      => "whois.afilias.net",
        "redstone"                 => "whois.afilias-srs.net",
        "rehab"                    => "whois.rightside.co",
        "reise"                    => "whois.nic.reise",
        "reisen"                   => "whois.donuts.co",
        "reit"                     => "whois.nic.reit",
        "rent"                     => "whois.nic.rent",
        "rentals"                  => "whois.donuts.co",
        "repair"                   => "whois.donuts.co",
        "report"                   => "whois.donuts.co",
        "republican"               => "whois.rightside.co",
        "rest"                     => "whois.nic.rest",
        "restaurant"               => "whois.donuts.co",
        "review"                   => "whois.nic.review",
        "reviews"                  => "whois.unitedtld.com",
        "rich"                     => "whois.afilias-srs.net",
        "ricoh"                    => "whois.nic.ricoh",
        "rio"                      => "whois.gtlds.nic.br",
        "rip"                      => "whois.rightside.co",
        "ro"                       => "whois.rotld.ro",
        "rocks"                    => "whois.unitedtld.com",
        "rodeo"                    => "whois-dub.mm-registry.com",
        "rs"                       => "whois.rnids.rs",
        "rsvp"                     => "domain-registry-whois.l.google.com",
        "ru"                       => "whois.tcinet.ru",
        "edu.ru"                   => "whois.informika.ru",
        "ruhr"                     => "whois.nic.ruhr",
        "run"                      => "whois.donuts.co",
        "rw"                       => "www.nic.rw",
        "sa"                       => "whois.nic.net.sa",
        "saarland"                 => "whois.ksregistry.net",
        "sale"                     => "whois.rightside.co",
        "sandvik"                  => "whois.nic.sandvik",
        "sandvikcoromant"          => "whois.nic.sandvikcoromant",
        "sanofi"                   => "whois.nic.sanofi",
        "sap"                      => "whois.nic.sap",
        "sarl"                     => "whois.donuts.co",
        "samsung"                  => "whois.nic.samsung",
        "saxo"                     => "whois.aridnrs.net.au",
        "sb"                       => "whois.nic.net.sb",
        "sc"                       => "whois2.afilias-grs.net",
        "sca"                      => "whois.nic.sca",
        "scb"                      => "whois.nic.scb",
        "schmidt"                  => "whois.nic.schmidt",
        "scholarships"             => "whois.afilias-srs.net",
        "school"                   => "whois.donuts.co",
        "schule"                   => "whois.donuts.co",
        "schwarz"                  => "whois.nic.schwarz",
        "science"                  => "whois.nic.science",
        "scor"                     => "whois.nic.scor",
        "scot"                     => "whois.scot.coreregistry.net",
        "se"                       => "whois.iis.se",
        "com.se"                   => "whois.centralnic.com",
        "seat"                     => "whois.nic.seat",
        "security"                 => "whois.nic.security",
        "seek"                     => "whois.nic.seek",
        "services"                 => "whois.donuts.co",
        "seven"                    => "whois.nic.seven",
        "sew"                      => "whois.afilias-srs.net",
        "sex"                      => "whois.afilias-srs.net",
        "sexy"                     => "whois.uniregistry.net",
        "sg"                       => "whois.sgnic.sg",
        "sh"                       => "whois.nic.sh",
        "shiksha"                  => "whois.afilias.net",
        "shoes"                    => "whois.donuts.co",
        "show"                     => "whois.donuts.co",
        "shriram"                  => "whois.afilias-srs.net",
        "si"                       => "whois.register.si",
        "singles"                  => "whois.donuts.co",
        "site"                     => "whois.centralnic.com",
        "sj"                       => "whois.ripe.net",
        "sk"                       => "whois.sk-nic.sk",
        "ski"                      => "whois.ksregistry.net",
        "sky"                      => "whois.nic.sky",
        "sl"                       => "whois.nic.sl",
        "sm"                       => "whois.nic.sm",
        "sn"                       => "whois.nic.sn",
        "sncf"                     => "whois-sncf.nic.fr",
        "so"                       => "whois.nic.so",
        "soccer"                   => "whois.donuts.co",
        "social"                   => "whois.unitedtld.com",
        "software"                 => "whois.rightside.co",
        "solar"                    => "whois.donuts.co",
        "solutions"                => "whois.donuts.co",
        "sony"                     => "whois.nic.sony",
        "soy"                      => "domain-registry-whois.l.google.com",
        "space"                    => "whois.nic.space",
        "spiegel"                  => "whois.ksregistry.net",
        "spreadbetting"            => "whois.nic.spreadbetting",
        "srl"                      => "whois.afilias-srs.net",
        "st"                       => "whois.nic.st",
        "stada"                    => "whois.afilias-srs.net",
        "starhub"                  => "whois.nic.starhub",
        "statoil"                  => "whois.nic.statoil",
        "stc"                      => "whois.centralnic.com",
        "stcgroup"                 => "whois.centralnic.com",
        "stockholm"                => "whois.afilias-srs.net",
        "studio"                   => "whois.rightside.co",
        "study"                    => "whois.nic.study",
        "style"                    => "whois.donuts.co",
        "su"                       => "whois.tcinet.ru",
        "sucks"                    => "whois.nic.sucks",
        "supplies"                 => "whois.donuts.co",
        "supply"                   => "whois.donuts.co",
        "support"                  => "whois.donuts.co",
        "surf"                     => "whois-dub.mm-registry.com",
        "surgery"                  => "whois.donuts.co",
        "swatch"                   => "whois.nic.swatch",
        "swiss"                    => "whois.nic.swiss",
        "sx"                       => "whois.sx",
        "sy"                       => "whois.tld.sy",
        "sydney"                   => "whois.nic.sydney",
        "systems"                  => "whois.donuts.co",
        "taipei"                   => "whois.nic.taipei",
        "tatamotors"               => "whois.nic.tatamotors",
        "tatar"                    => "whois.nic.tatar",
        "tattoo"                   => "whois.uniregistry.net",
        "tax"                      => "whois.donuts.co",
        "taxi"                     => "whois.donuts.co",
        "tc"                       => "whois.nic.tc",
        "team"                     => "whois.donuts.co",
        "tech"                     => "whois.nic.tech",
        "technology"               => "whois.donuts.co",
        "tel"                      => "whois.nic.tel",
        "telefonica"               => "whois-fe.telefonica.tango.knipp.de",
        "temasek"                  => "whois.afilias-srs.net",
        "tennis"                   => "whois.donuts.co",
        "tf"                       => "whois.nic.tf",
        "tg"                       => "www.netmaster.tg",
        "th"                       => "whois.thnic.co.th",
        "thd"                      => "whois.afilias-srs.net",
        "theater"                  => "whois.donuts.co",
        "theatre"                  => "whois.nic.theatre",
        "tickets"                  => "whois.nic.tickets",
        "tienda"                   => "whois.donuts.co",
        "tips"                     => "whois.donuts.co",
        "tires"                    => "whois.donuts.co",
        "tirol"                    => "whois.nic.tirol",
        "tj"                       => "www.nic.tj",
        "tk"                       => "whois.dot.tk",
        "tl"                       => "whois.nic.tl",
        "tm"                       => "whois.nic.tm",
        "tn"                       => "whois.ati.tn",
        "to"                       => "whois.tonic.to",
        "today"                    => "whois.donuts.co",
        "tools"                    => "whois.donuts.co",
        "top"                      => "whois.nic.top",
        "toray"                    => "whois.nic.toray",
        "toshiba"                  => "whois.nic.toshiba",
        "tours"                    => "whois.donuts.co",
        "town"                     => "whois.donuts.co",
        "toyota"                   => "whois.nic.toyota",
        "toys"                     => "whois.donuts.co",
        "tr"                       => "whois.nic.tr",
        "trade"                    => "whois.nic.trade",
        "trading"                  => "whois.nic.trading",
        "training"                 => "whois.donuts.co",
        "travel"                   => "whois.nic.travel",
        "trust"                    => "whois.nic.trust",
        "tt"                       => "www.nic.tt",
        "tui"                      => "whois.ksregistry.net",
        "tv"                       => "tvwhois.verisign-grs.com",
        "tw"                       => "whois.twnic.net.tw",
        "tz"                       => "whois.tznic.or.tz",
        "ua"                       => "whois.ua",
        "biz.ua"                   => "whois.biz.ua",
        "co.ua"                    => "whois.co.ua",
        "in.ua"                    => "whois.in.ua",
        "net.ua"                   => "whois.net.ua",
        "pp.ua"                    => "whois.pp.ua",
        "ubs"                      => "whois.nic.ubs",
        "ug"                       => "whois.co.ug",
        "uk"                       => "whois.nic.uk",
        "ac.uk"                    => "whois.ja.net",
        "gov.uk"                   => "whois.ja.net",
        "university"               => "whois.donuts.co",
        "uno"                      => "whois.nic.uno",
        "uol"                      => "whois.gtlds.nic.br",
        "us"                       => "whois.nic.us",
        "fed.us"                   => "whois.nic.gov",
        "uy"                       => "whois.nic.org.uy",
        "com.uy"                   => "dns.antel.net.uy",
        "uz"                       => "whois.cctld.uz",
        "co.uz"                    => "whois.reg.uz",
        "com.uz"                   => "whois.reg.uz",
        "va"                       => "whois.ripe.net",
        "vacations"                => "whois.donuts.co",
        "vc"                       => "whois2.afilias-grs.net",
        "ve"                       => "whois.nic.ve",
        "vegas"                    => "whois.afilias-srs.net",
        "ventures"                 => "whois.donuts.co",
        "versicherung"             => "whois.nic.versicherung",
        "vet"                      => "whois.rightside.co",
        "vg"                       => "whois.nic.vg",
        "vi"                       => "www.nic.vi",
        "viajes"                   => "whois.donuts.co",
        "video"                    => "whois.rightside.co",
        "villas"                   => "whois.donuts.co",
        "vin"                      => "whois.donuts.co",
        "virgin"                   => "whois.nic.virgin",
        "vision"                   => "whois.donuts.co",
        "vista"                    => "whois.nic.vista",
        "vistaprint"               => "whois.nic.vistaprint",
        "viva"                     => "whois.centralnic.com",
        "vlaanderen"               => "whois.nic.vlaanderen",
        "vn"                       => "www.vnnic.net.vn",
        "vodka"                    => "whois-dub.mm-registry.com",
        "vote"                     => "whois.afilias.net",
        "voting"                   => "whois.voting.tld-box.at",
        "voto"                     => "whois.afilias.net",
        "voyage"                   => "whois.donuts.co",
        "vu"                       => "vunic.vu",
        "wales"                    => "whois.nic.wales",
        "walter"                   => "whois.nic.walter",
        "wang"                     => "whois.gtld.knet.cn",
        "watch"                    => "whois.donuts.co",
        "webcam"                   => "whois.nic.webcam",
        "website"                  => "whois.nic.website",
        "wed"                      => "whois.nic.wed",
        "wedding"                  => "whois-dub.mm-registry.com",
        "wf"                       => "whois.nic.wf",
        "whoswho"                  => "whois.nic.whoswho",
        "wien"                     => "whois.nic.wien",
        "wiki"                     => "whois.nic.wiki",
        "win"                      => "whois.nic.win",
        "wine"                     => "whois.donuts.co",
        "wme"                      => "whois.nic.wme",
        "work"                     => "whois-dub.mm-registry.com",
        "works"                    => "whois.donuts.co",
        "world"                    => "whois.donuts.co",
        "ws"                       => "whois.website.ws",
        "wtc"                      => "whois.nic.wtc",
        "wtf"                      => "whois.donuts.co",
        "xerox"                    => "whois.nic.xerox",
        "xin"                      => "whois.afilias-srs.net",
        "xperia"                   => "whois.nic.xperia",
        "xxx"                      => "whois.nic.xxx",
        "xyz"                      => "whois.nic.xyz",
        "yachts"                   => "whois.afilias-srs.net",
        "yodobashi"                => "whois.nic.gmo",
        "yoga"                     => "whois-dub.mm-registry.com",
        "youtube"                  => "domain-registry-whois.l.google.com",
        "yt"                       => "whois.nic.yt",
        "ac.za"                    => "whois.ac.za",
        "org.za"                   => "whois.org.za",
        "co.za"                    => "whois.co.za",
        "net.za"                   => "whois.net.za",
        "nom.za"                   => "whois.nom.za",
        "web.za"                   => "whois.web.za",
        "zip"                      => "domain-registry-whois.l.google.com",
        "zm"                       => "whois.nic.zm",
        "zone"                     => "whois.donuts.co",
        "zuerich"                  => "whois.ksregistry.net",
        "co.zw"                    => "www.zispa.co.zw",
        "xn--11b4c3d"              => "whois.nic.xn--11b4c3d",
        "xn--1qqw23a"              => "whois.ngtld.cn",
        "xn--30rr7y"               => "whois.nic.wang",
        "xn--3bst00m"              => "whois.gtld.knet.cn",
        "xn--3ds443g"              => "whois.afilias-srs.net",
        "xn--3e0b707e"             => "whois.kr",
        "xn--3pxu8k"               => "whois.nic.xn--3pxu8k",
        "xn--42c2d9a"              => "whois.nic.xn--42c2d9a",
        "xn--45q11c"               => "whois.nic.xn--45q11c",
        "xn--4gbrim"               => "whois.afilias-srs.net",
        "xn--55qw42g"              => "whois.conac.cn",
        "xn--55qx5d"               => "whois.ngtld.cn",
        "xn--6frz82g"              => "whois.afilias.net",
        "xn--6qq986b3xl"           => "whois.gtld.knet.cn",
        "xn--80adxhks"             => "whois.nic.xn--80adxhks",
        "xn--80ao21a"              => "whois.nic.kz",
        "xn--80asehdb"             => "whois.online.rs.corenic.net",
        "xn--80aswg"               => "whois.site.rs.corenic.net",
        "xn--90a3ac"               => "whois.rnids.rs",
        "xn--90ais"                => "whois.cctld.by",
        "xn--9dbq2a"               => "whois.nic.xn--9dbq2a",
        "xn--9et52u"               => "whois.nic.wang",
        "xn--b4w605ferd"           => "whois.afilias-srs.net",
        "xn--c1avg"                => "whois.publicinterestregistry.net",
        "xn--c2br7g"               => "whois.nic.xn--c2br7g",
        "xn--cg4bki"               => "whois.kr",
        "xn--clchc0ea0b2g2a9gcd"   => "whois.sgnic.sg",
        "xn--czrs0t"               => "whois.donuts.co",
        "xn--czru2d"               => "whois.gtld.knet.cn",
        "xn--d1acj3b"              => "whois.nic.xn--d1acj3b",
        "xn--d1alf"                => "whois.marnet.mk",
        "xn--efvy88h"              => "whois.nic.xn--efvy88h",
        "xn--estv75g"              => "whois.afilias-srs.net",
        "xn--fhbei"                => "whois.nic.xn--fhbei",
        "xn--fiq228c5hs"           => "whois.afilias-srs.net",
        "xn--fiq64b"               => "whois.gtld.knet.cn",
        "xn--fiqs8s"               => "cwhois.cnnic.cn",
        "xn--fiqz9s"               => "cwhois.cnnic.cn",
        "xn--fjq720a"              => "whois.donuts.co",
        "xn--flw351e"              => "domain-registry-whois.l.google.com",
        "xn--fzc2c9e2c"            => "whois.nic.lk",
        "xn--hxt814e"              => "whois.nic.xn--hxt814e",
        "xn--i1b6b1a6a2e"          => "whois.publicinterestregistry.net",
        "xn--io0a7i"               => "whois.ngtld.cn",
        "xn--j1aef"                => "whois.nic.xn--j1aef",
        "xn--j6w193g"              => "whois.hkirc.hk",
        "xn--j1amh"                => "whois.dotukr.com",
        "xn--kcrx77d1x4a"          => "whois.nic.xn--kcrx77d1x4a",
        "xn--kprw13d"              => "whois.twnic.net.tw",
        "xn--kpry57d"              => "whois.twnic.net.tw",
        "xn--kput3i"               => "whois.afilias-srs.net",
        "xn--lgbbat1ad8j"          => "whois.nic.dz",
        "xn--mgb9awbf"             => "whois.registry.om",
        "xn--mgba3a4f16a"          => "whois.nic.ir",
        "xn--mgbaam7a8h"           => "whois.aeda.net.ae",
        "xn--mgbab2bd"             => "whois.bazaar.coreregistry.net",
        "xn--mgberp4a5d4ar"        => "whois.nic.net.sa",
        "xn--mgbx4cd0ab"           => "whois.mynic.my",
        "xn--mk1bu44c"             => "whois.nic.xn--mk1bu44c",
        "xn--mxtq1m"               => "whois.nic.xn--mxtq1m",
        "xn--ngbc5azd"             => "whois.nic.xn--ngbc5azd",
        "xn--node"                 => "whois.itdc.ge",
        "xn--nqv7f"                => "whois.publicinterestregistry.net",
        "xn--nqv7fs00ema"          => "whois.publicinterestregistry.net",
        "xn--o3cw4h"               => "whois.thnic.co.th",
        "xn--ogbpf8fl"             => "whois.tld.sy",
        "xn--p1acf"                => "whois.nic.xn--p1acf",
        "xn--p1ai"                 => "whois.tcinet.ru",
        "xn--pssy2u"               => "whois.nic.xn--pssy2u",
        "xn--q9jyb4c"              => "domain-registry-whois.l.google.com",
        "xn--qcka1pmc"             => "domain-registry-whois.l.google.com",
        "xn--ses554g"              => "whois.registry.knet.cn",
        "xn--t60b56a"              => "whois.nic.xn--t60b56a",
        "xn--tckwe"                => "whois.nic.xn--tckwe",
        "xn--unup4y"               => "whois.donuts.co",
        "xn--vermgensberater-ctb"  => "whois.ksregistry.net",
        "xn--vermgensberatung-pwb" => "whois.ksregistry.net",
        "xn--vhquv"                => "whois.donuts.co",
        "xn--vuq861b"              => "whois.ngtld.cn",
        "xn--wgbl6a"               => "whois.registry.qa",
        "xn--xhq521b"              => "whois.ngtld.cn",
        "xn--xkc2al3hye2a"         => "whois.nic.lk",
        "xn--y9a3aq"               => "whois.amnic.net",
        "xn--yfro4i67o"            => "whois.sgnic.sg",
        "xn--ygbi2ammx"            => "whois.pnina.ps",
        "xn--zfr164b"              => "whois.conac.cn",
        "abkhazia.su"              => "whois.nic.ru",
        "jambyl.su"                => "whois.nic.ru",
        "navoi.su"                 => "whois.nic.ru",
        "adygeya.ru"               => "whois.nic.ru",
        "kalmykia.ru"              => "whois.nic.ru",
        "north-kazakhstan.su"      => "whois.nic.ru",
        "adygeya.su"               => "whois.nic.ru",
        "kalmykia.su"              => "whois.nic.ru",
        "nov.ru"                   => "whois.nic.ru",
        "aktyubinsk.su"            => "whois.nic.ru",
        "kaluga.su"                => "whois.nic.ru",
        "nov.su"                   => "whois.nic.ru",
        "arkhangelsk.su"           => "whois.nic.ru",
        "karacol.su"               => "whois.nic.ru",
        "obninsk.su"               => "whois.nic.ru",
        "armenia.su"               => "whois.nic.ru",
        "karaganda.su"             => "whois.nic.ru",
        "penza.su"                 => "whois.nic.ru",
        "ashgabad.su"              => "whois.nic.ru",
        "karelia.su"               => "whois.nic.ru",
        "pokrovsk.su"              => "whois.nic.ru",
        "azerbaijan.su"            => "whois.nic.ru",
        "khakassia.su"             => "whois.nic.ru",
        "pyatigorsk.ru"            => "whois.nic.ru",
        "balashov.su"              => "whois.nic.ru",
        "krasnodar.su"             => "whois.nic.ru",
        "sochi.su"                 => "whois.nic.ru",
        "bashkiria.ru"             => "whois.nic.ru",
        "kurgan.su"                => "whois.nic.ru",
        "spb.ru"                   => "whois.nic.ru",
        "bashkiria.su"             => "whois.nic.ru",
        "kustanai.ru"              => "whois.nic.ru",
        "spb.su"                   => "whois.nic.ru",
        "bir.ru"                   => "whois.nic.ru",
        "kustanai.su"              => "whois.nic.ru",
        "tashkent.su"              => "whois.nic.ru",
        "bryansk.su"               => "whois.nic.ru",
        "lenug.su"                 => "whois.nic.ru",
        "termez.su"                => "whois.nic.ru",
        "bukhara.su"               => "whois.nic.ru",
        "mangyshlak.su"            => "whois.nic.ru",
        "togliatti.su"             => "whois.nic.ru",
        "cbg.ru"                   => "whois.nic.ru",
        "marine.ru"                => "whois.nic.ru",
        "troitsk.su"               => "whois.nic.ru",
        "chimkent.su"              => "whois.nic.ru",
        "mordovia.ru"              => "whois.nic.ru",
        "tselinograd.su"           => "whois.nic.ru",
        "dagestan.ru"              => "whois.nic.ru",
        "mordovia.su"              => "whois.nic.ru",
        "tula.su"                  => "whois.nic.ru",
        "dagestan.su"              => "whois.nic.ru",
        "msk.ru"                   => "whois.nic.ru",
        "tuva.su"                  => "whois.nic.ru",
        "east-kazakhstan.su"       => "whois.nic.ru",
        "msk.su"                   => "whois.nic.ru",
        "vladikavkaz.ru"           => "whois.nic.ru",
        "georgia.su"               => "whois.nic.ru",
        "murmansk.su"              => "whois.nic.ru",
        "vladikavkaz.su"           => "whois.nic.ru",
        "grozny.ru"                => "whois.nic.ru",
        "mytis.ru"                 => "whois.nic.ru",
        "vladimir.ru"              => "whois.nic.ru",
        "grozny.su"                => "whois.nic.ru",
        "nalchik.ru"               => "whois.nic.ru",
        "vladimir.su"              => "whois.nic.ru",
        "ivanovo.su"               => "whois.nic.ru",
        "nalchik.su"               => "whois.nic.ru",
        "vologda.su"               => "whois.nic.ru",
        "xn--j1aef.xn--p1ai"       => "whois.webnames.ru",
        "xn--e1apq.xn--p1ai"       => "whois.webnames.ru",
        "xn--c1avg.xn--p1ai"       => "whois.webnames.ru",
        //"default"                => "whois.internic.net",
    );

    const IPV4_REGISTRIES = array(
        "000" => "reserved",
        "001" => "whois.apnic.net",
        "002" => "whois.ripe.net",
        "003" => "whois.arin.net",
        "004" => "whois.arin.net",
        "005" => "whois.ripe.net",
        "006" => "whois.arin.net",
        "007" => "whois.arin.net",
        "008" => "whois.arin.net",
        "009" => "whois.arin.net",
        "010" => "reserved",
        "011" => "whois.arin.net",
        "012" => "whois.arin.net",
        "013" => "whois.arin.net",
        "014" => "whois.apnic.net",
        "015" => "whois.arin.net",
        "016" => "whois.arin.net",
        "017" => "whois.arin.net",
        "018" => "whois.arin.net",
        "019" => "whois.arin.net",
        "020" => "whois.arin.net",
        "021" => "whois.arin.net",
        "022" => "whois.arin.net",
        "023" => "whois.arin.net",
        "024" => "whois.arin.net",
        "025" => "whois.ripe.net",
        "026" => "whois.arin.net",
        "027" => "whois.apnic.net",
        "028" => "whois.arin.net",
        "029" => "whois.arin.net",
        "030" => "whois.arin.net",
        "031" => "whois.ripe.net",
        "032" => "whois.arin.net",
        "033" => "whois.arin.net",
        "034" => "whois.arin.net",
        "035" => "whois.arin.net",
        "036" => "whois.apnic.net",
        "037" => "whois.ripe.net",
        "038" => "whois.arin.net",
        "039" => "whois.apnic.net",
        "040" => "whois.arin.net",
        "041" => "whois.afrinic.net",
        "042" => "whois.apnic.net",
        "043" => "whois.apnic.net",
        "044" => "whois.arin.net",
        "045" => "whois.arin.net",
        "046" => "whois.ripe.net",
        "047" => "whois.arin.net",
        "048" => "whois.arin.net",
        "049" => "whois.apnic.net",
        "050" => "whois.arin.net",
        "051" => "whois.ripe.net",
        "052" => "whois.arin.net",
        "053" => "whois.ripe.net",
        "054" => "whois.arin.net",
        "055" => "whois.arin.net",
        "056" => "whois.arin.net",
        "057" => "whois.ripe.net",
        "058" => "whois.apnic.net",
        "059" => "whois.apnic.net",
        "060" => "whois.apnic.net",
        "061" => "whois.apnic.net",
        "062" => "whois.ripe.net",
        "063" => "whois.arin.net",
        "064" => "whois.arin.net",
        "065" => "whois.arin.net",
        "066" => "whois.arin.net",
        "067" => "whois.arin.net",
        "068" => "whois.arin.net",
        "069" => "whois.arin.net",
        "070" => "whois.arin.net",
        "071" => "whois.arin.net",
        "072" => "whois.arin.net",
        "073" => "whois.arin.net",
        "074" => "whois.arin.net",
        "075" => "whois.arin.net",
        "076" => "whois.arin.net",
        "077" => "whois.ripe.net",
        "078" => "whois.ripe.net",
        "079" => "whois.ripe.net",
        "080" => "whois.ripe.net",
        "081" => "whois.ripe.net",
        "082" => "whois.ripe.net",
        "083" => "whois.ripe.net",
        "084" => "whois.ripe.net",
        "085" => "whois.ripe.net",
        "086" => "whois.ripe.net",
        "087" => "whois.ripe.net",
        "088" => "whois.ripe.net",
        "089" => "whois.ripe.net",
        "090" => "whois.ripe.net",
        "091" => "whois.ripe.net",
        "092" => "whois.ripe.net",
        "093" => "whois.ripe.net",
        "094" => "whois.ripe.net",
        "095" => "whois.ripe.net",
        "096" => "whois.arin.net",
        "097" => "whois.arin.net",
        "098" => "whois.arin.net",
        "099" => "whois.arin.net",
        "100" => "whois.arin.net",
        "101" => "whois.apnic.net",
        "102" => "whois.afrinic.net",
        "103" => "whois.apnic.net",
        "104" => "whois.arin.net",
        "105" => "whois.afrinic.net",
        "106" => "whois.apnic.net",
        "107" => "whois.arin.net",
        "108" => "whois.arin.net",
        "109" => "whois.ripe.net",
        "110" => "whois.apnic.net",
        "111" => "whois.apnic.net",
        "112" => "whois.apnic.net",
        "113" => "whois.apnic.net",
        "114" => "whois.apnic.net",
        "115" => "whois.apnic.net",
        "116" => "whois.apnic.net",
        "117" => "whois.apnic.net",
        "118" => "whois.apnic.net",
        "119" => "whois.apnic.net",
        "120" => "whois.apnic.net",
        "121" => "whois.apnic.net",
        "122" => "whois.apnic.net",
        "123" => "whois.apnic.net",
        "124" => "whois.apnic.net",
        "125" => "whois.apnic.net",
        "126" => "whois.apnic.net",
        "127" => "reserved",
        "128" => "whois.arin.net",
        "129" => "whois.arin.net",
        "130" => "whois.arin.net",
        "131" => "whois.arin.net",
        "132" => "whois.arin.net",
        "133" => "whois.apnic.net",
        "134" => "whois.arin.net",
        "135" => "whois.arin.net",
        "136" => "whois.arin.net",
        "137" => "whois.arin.net",
        "138" => "whois.arin.net",
        "139" => "whois.arin.net",
        "140" => "whois.arin.net",
        "141" => "whois.ripe.net",
        "142" => "whois.arin.net",
        "143" => "whois.arin.net",
        "144" => "whois.arin.net",
        "145" => "whois.ripe.net",
        "146" => "whois.arin.net",
        "147" => "whois.arin.net",
        "148" => "whois.arin.net",
        "149" => "whois.arin.net",
        "150" => "whois.apnic.net",
        "151" => "whois.ripe.net",
        "152" => "whois.arin.net",
        "153" => "whois.apnic.net",
        "154" => "whois.afrinic.net",
        "155" => "whois.arin.net",
        "156" => "whois.arin.net",
        "157" => "whois.arin.net",
        "158" => "whois.arin.net",
        "159" => "whois.arin.net",
        "160" => "whois.arin.net",
        "161" => "whois.arin.net",
        "162" => "whois.arin.net",
        "163" => "whois.apnic.net",
        "164" => "whois.arin.net",
        "165" => "whois.arin.net",
        "166" => "whois.arin.net",
        "167" => "whois.arin.net",
        "168" => "whois.arin.net",
        "169" => "whois.arin.net",
        "170" => "whois.arin.net",
        "171" => "whois.apnic.net",
        "172" => "whois.arin.net",
        "173" => "whois.arin.net",
        "174" => "whois.arin.net",
        "175" => "whois.apnic.net",
        "176" => "whois.ripe.net",
        "177" => "whois.lacnic.net",
        "178" => "whois.ripe.net",
        "179" => "whois.lacnic.net",
        "180" => "whois.apnic.net",
        "181" => "whois.lacnic.net",
        "182" => "whois.apnic.net",
        "183" => "whois.apnic.net",
        "184" => "whois.arin.net",
        "185" => "whois.ripe.net",
        "186" => "whois.lacnic.net",
        "187" => "whois.lacnic.net",
        "188" => "whois.ripe.net",
        "189" => "whois.lacnic.net",
        "190" => "whois.lacnic.net",
        "191" => "whois.lacnic.net",
        "192" => "whois.arin.net",
        "193" => "whois.ripe.net",
        "194" => "whois.ripe.net",
        "195" => "whois.ripe.net",
        "196" => "whois.afrinic.net",
        "197" => "whois.afrinic.net",
        "198" => "whois.arin.net",
        "199" => "whois.arin.net",
        "200" => "whois.lacnic.net",
        "201" => "whois.lacnic.net",
        "202" => "whois.apnic.net",
        "203" => "whois.apnic.net",
        "204" => "whois.arin.net",
        "205" => "whois.arin.net",
        "206" => "whois.arin.net",
        "207" => "whois.arin.net",
        "208" => "whois.arin.net",
        "209" => "whois.arin.net",
        "210" => "whois.apnic.net",
        "211" => "whois.apnic.net",
        "212" => "whois.ripe.net",
        "213" => "whois.ripe.net",
        "214" => "whois.arin.net",
        "215" => "whois.arin.net",
        "216" => "whois.arin.net",
        "217" => "whois.ripe.net",
        "218" => "whois.apnic.net",
        "219" => "whois.apnic.net",
        "220" => "whois.apnic.net",
        "221" => "whois.apnic.net",
        "222" => "whois.apnic.net",
        "223" => "whois.apnic.net",
        "224" => "reserved",
        "225" => "reserved",
        "226" => "reserved",
        "227" => "reserved",
        "228" => "reserved",
        "229" => "reserved",
        "230" => "reserved",
        "231" => "reserved",
        "232" => "reserved",
        "233" => "reserved",
        "234" => "reserved",
        "235" => "reserved",
        "236" => "reserved",
        "237" => "reserved",
        "238" => "reserved",
        "239" => "reserved",
        "240" => "reserved",
        "241" => "reserved",
        "242" => "reserved",
        "243" => "reserved",
        "244" => "reserved",
        "245" => "reserved",
        "246" => "reserved",
        "247" => "reserved",
        "248" => "reserved",
        "249" => "reserved",
        "250" => "reserved",
        "251" => "reserved",
        "252" => "reserved",
        "253" => "reserved",
        "254" => "reserved",
        "255" => "reserved",
    );

    const IPV6_REGISTRIES = array(
        "2001" => array(
            "0200" => "whois.apnic.net",
            "0400" => "whois.arin.net",
            "0600" => "whois.ripe.net",
            "0800" => "whois.ripe.net",
            "0a00" => "whois.ripe.net",
            "0c00" => "whois.apnic.net",
            "0e00" => "whois.apnic.net",
            "1200" => "whois.lacnic.net",
            "1400" => "whois.ripe.net",
            "1600" => "whois.ripe.net",
            "1800" => "whois.arin.net",
            "1a00" => "whois.ripe.net",
            "1c00" => "whois.ripe.net",
            "2000" => "whois.ripe.net",
            "3000" => "whois.ripe.net",
            "3800" => "whois.ripe.net",
            "3c00" => "reserved",
            "4000" => "whois.ripe.net",
            "4200" => "whois.afrinic.net",
            "4400" => "whois.apnic.net",
            "4600" => "whois.ripe.net",
            "4800" => "whois.arin.net",
            "4a00" => "whois.ripe.net",
            "4c00" => "whois.ripe.net",
            "5000" => "whois.ripe.net",
            "8000" => "whois.apnic.net",
            "a000" => "whois.apnic.net",
            "b000" => "whois.apnic.net",
        ),
        "2002" => "reserved",
        "2003" => "whois.ripe.net",
        "2400" => "whois.apnic.net",
        "2600" => "whois.arin.net",
        "2610" => "whois.arin.net",
        "2620" => "whois.arin.net",
        "2800" => "whois.lacnic.net",
        "2a00" => "whois.ripe.net",
        "2c00" => "whois.afrinic.net",
        "2d00" => "reserved",
        "2e00" => "reserved",
        "3000" => "reserved",
        "3ffe" => "reserved",
        "5f00" => "reserved",
    );
}
